### ISSUE TITLE
Please release 3.0.1

### ISSUE THREAD

**Issue by jacob-ebey** [web-std/io#41]
Seems that the release yesterday did not make it's way to NPM.
<img width="547" alt="image" src="https://user-images.githubusercontent.com/12063586/150437226-e4784ee7-fc2e-4a2d-ab99-36ae439868a2.png">

**Comment by jacob-ebey** [comment]
CC @Gozala

**Comment by Gozala** [comment]
Sorry for that, looks like concurrent merges confuse the release jobs. I believe all should be out now
