### ISSUE TITLE
`fetch` is at `2.0.1` but package.json in repo is `2.0.0`

### ISSUE THREAD

**Issue by olizilla** [web-std/io#6]
@web-std/fetch is at `2.0.1` on the [registry](https://www.npmjs.com/package/@web-std/fetch), but the repo package.json is at `2.0.0` https://github.com/web-std/io/blob/68e89a806cd195bffa85cc5a8485711905761376/fetch/package.json#L3

**Comment by revelt** [comment]
Let's close this issue, the latest is `3.0.0` and in sync in both places.
