### ISSUE TITLE
Form data util does not use @web-std/file

### ISSUE THREAD

**Issue by benmerckx** [web-std/io#63]
https://github.com/web-std/io/blob/c88170bf24f064adfbb3586a21fb76650ca5a9ab/packages/fetch/src/utils/form-data.js#L107

The `File` instance being constructed here is not imported from `@web-std/file` causing it to fail in node with 

````
ReferenceError: File is not defined
````

**Comment by Gozala** [comment]
Thanks for catching this @benmerckx would you be interested in contributing a fix ?

**Comment by MichaelDeBoey** [comment]
Closed by #68
